'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

https://projecteuler.net/problem=2
'''
import math

def sumThirdFibbo(m):
       vec = [1,2]
       fsum = 2
       while 1:
              fn = 0
              for j in range(3):
              '''
              Every 3rd fibbonacci number is even:
              http://math.stackexchange.com/questions/60340/fibonacci-modular-results
              '''
                     global fn
                     fn = vec[0]+vec[1]
                     vec[0]=vec[1]
                     vec[1]=fn
              if fn >= m:
                     return fsum
              else:
                     fsum+=vec[1]
                     
